### ISSUE TITLE
Result 这个 model 写的好差劲

### ISSUE THREAD

**Issue by zieglar** [yunpian/yunpian-php-sdk#10]
怎么获取里面的 data

**Comment by zieglar** [comment]
非要这样写才行 $tpls->data(null)
一点都不友好

**Comment by zieglar** [comment]
非要这样写才行 $tpls->data(null)
一点都不友好

$clnt->tpl()->get([])->data(null)

这是一个获取所有模版的写法，槽点满满

**Comment by dzh** [comment]
@zieglar 这个抱歉，没写好，在1.0.1里已设置默认值，现在可以$r->data()
