### ISSUE TITLE
如何解析返回的数据呢？

### ISSUE THREAD

**Issue by tanggaolin** [yunpian/yunpian-php-sdk#16]
$r = $clnt->sms()->single_send($param);
这个$r 为一个对象，想咨询下如何解析获取相应的值呢
我转为数组就是这样的
array(5) {
  ["Yunpian\Sdk\Model\Resultcode"]=>
  int(0)
  ["Yunpian\Sdk\Model\Resultmsg"]=>
  string(12) "发送成功"
  ["Yunpian\Sdk\Model\Resultdetail"]=>
  NULL
  ["Yunpian\Sdk\Model\Resulte"]=>
  NULL
  ["Yunpian\Sdk\Model\Resultdata"]=>
  array(7) {
    ["code"]=>
    int(0)
    ["msg"]=>
    string(12) "发送成功"
    ["count"]=>
    int(1)
    ["fee"]=>
    float(0.05)
    ["unit"]=>
    string(3) "RMB"
    ["mobile"]=>
    string(11) "15170973248"
    ["sid"]=>
    int(17842692668)
  }
}

**Comment by dzh** [comment]
@TangGaolin 取值的如$r->code()获取返回码,$r->data()获取返回数据（正确返回时）

**Comment by tanggaolin** [comment]
谢谢指导了
