### ISSUE TITLE
希望可以配置是否需要进行ssl认证

### ISSUE THREAD

**Issue by lixinyuan1213** [yunpian/yunpian-php-sdk#23]
如果不做修改，直接使用会出现如下错误：cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

希望可以添加一个配置选项，用开发者自行选择是否使用安全的认证方式。

**Comment by Woffee** [comment]
在 src/yunpian.ini 这个文件里，把 https 换成 http 就好了

**Comment by lixinyuan1213** [comment]
OK
