### ISSUE TITLE
作为一个官方的sdk这个质量真无力吐槽了，这叫Demo不叫SDK

### ISSUE THREAD

**Issue by DYFeng** [yunpian/yunpian-php-sdk#3]
什么时候能放composer？

**Comment by linjiaqi86** [comment]
感谢你的反馈！我们会尽快优化一下

**Comment by yushine** [comment]
建议收编 
https://github.com/argb/yunpian-sms

**Comment by DYFeng** [comment]
虽然我不想补刀,但  https://github.com/argb/yunpian-sms 才真正像一个项目,可移植性封装,单元测试,ci,文档...官方可以参考下

**Comment by dzh** [comment]
yunpian-php-sdk正式版1.0.0已发布到Composer,支持所有Rest Api。谢谢大家的建议，欢迎pull request。
